spring:
  application:
    name: hotelapp-backend
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotelapp_2026_1
    username: postgres
    password: admin